services:
  backend:
    environment:
      HOME: /var/www
    build:
      context: ./docker/php
    container_name: properties-backend
    user: "${USER_ID:-1000}:${USER_ID:-1000}"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: php-fpm -R

  nginx:
    image: nginx:alpine
    container_name: properties-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  frontend:
    image: node:20-alpine
    container_name: properties-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
volumes:
  frontend_node_modules: