services:
  backend:
    build:
      context: ./docker/php
    container_name: notes-backend
    user: "${USER_ID:-1000}:${USER_ID:-1000}"
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: >
      sh -c "mkdir -p storage/logs bootstrap/cache database
      && touch storage/logs/laravel.log
      && chown -R www-data:www-data /var/www/html
      && chmod -R 777 storage bootstrap/cache database
      && php-fpm"

  nginx:
    image: nginx:alpine
    container_name: notes-nginx
    ports:
      - "80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    image: node:20-alpine
    container_name: notes-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
volumes:
  frontend_node_modules: